---
- hosts: '{{host}}' 
  remote_user: test100
  become: yes
  vars:
     pkg: httpd  #please enter package name 
  vars_files:
    - abc.yml
  vars_prompt:
    - name: pkg2
      prompt: enter package name
      private: no
  tasks:
   - name: Install {{pkg}} package
     yum: name={{pkg}} state=installed
   - name: install {{pkg1}} package
     yum: name={{pkg1}} state=installed
#   - name: install {{pkg2}} package
#     yum: name={{pkg2}} state=installed
   - name: create index.html file
     copy: src=index.html dest=/var/www/html
   - name: start httpd service
     service: name={{pkg}} state=started

